FROM node:24.1.0-alpine AS builder

WORKDIR /app

COPY package*.json ./

RUN npm ci

COPY . .

RUN npm run build

FROM node:24.1.0-alpine as runner

WORKDIR /app

ENV NODE_ENV=production
ENV PORT=8085

COPY --from=builder /app/package*.json ./
COPY --from=builder /app/node_modules ./node_modules
COPY --from-builder /app/.next ./.next
COPY --from=builder /app/public ./public

EXPOSE 8085

CMD ["npm", "start"]


