services:
    myportfolio:
        build:
            context: .
        container_name: portfolioNext
        networks:
            - main_network
        ports:
            - '5055:5055'
        volumes:
            - /root/main/portfolio_nextjs/.env:/app/.env
            - /root/main/portfolio_nextjs/emaildata.ts:/app/emaildata.ts
        environment:
            - NODE_ENV=production
            - PORT=5055
        restart: unless-stopped

networks:
    main_network:
        external: true
        name: main_network
