version: '3.8'

services:
    myportfolio:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '5055:5055'
        volumes:
            - /root/main/portfolio_nextjs/.env:/app/.env
            - /root/main/portfolio_nextjs/emaildata.ts:/app/emaildata.ts
        environment:
            - NODE_ENV=production
            - PORT=8085
        restart: unless-stopped
