services:
    myportfolio:
        build:
            context: .
            dockerfile: Dockerfile
        env_file:
            - .env
        container_name: portfolioNext
        networks:
            - main_network
        ports:
            - '5050:5050'
        volumes:
            - /root/main/portfolio_nextjs/.env:/app/.env
        environment:
            - NODE_ENV=production
            - PORT=5050
        restart: unless-stopped

networks:
    main_network:
        external: true
        name: main_network
