services:
    myportfolio:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: portfolioNext
        networks:
            - main_network
        ports:
            - '5050:5050'
        volumes:
            - /root/main/portfolio_nextjs/.env:/app/.env
            - /root/main/portfolio_nextjs/credentials:/app/credentials
            - /root/main/portfolio_nextjs/logs:/app/logs
        environment:
            - NODE_ENV=production
            - PORT=5055
        restart: unless-stopped

networks:
    main_network:
        external: true
        name: main_network
