version: '3.8'

services:
    my-portfolio:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '8085:8085'
        environment:
            - NODE_ENV=production
            - PORT=8085
        restart: unless-stopped
