export const APP_CONFIG = {
	nodeEnv: process.env.NODE_ENV,
	metrics: {
		enabled: true,
		protectWithToken: process.env.METRICS_BEARER_TOKEN,
		collectDefaultMetrics: true,
		prefix: process.env.METRICS_PREFIX ?? 'portfolio_',
	},
	auth: {
		secret: process.env.AUTH_SECRET,
		expiresIn: 24 * 60 * 60,
		cookie: {
			httpOnly: true,
			name: 'SESSID',
			path: '/control',
			sameSite: 'lax',
			secure: process.env.NODE_ENV === 'production',
		},
		localeCookie: {
			name: 'NEXT_LANG',
			path: '/',
			maxAge: 60 * 60 * 24 * 365,
			httpOnly: true,
			sameSite: 'lax',
			secure: process.env.NODE_ENV === 'production',
		},
	},
	contact: {
		defaultContactObject: {
			client: '',
			email: '',
			subject: '',
			content: '',
		},
	},
	redis: {
		enabled: process.env.REDIS_ENABLED === 'true',
		host: process.env.REDIS_HOST,
		port: process.env.REDIS_PORT,
		password: process.env.REDIS_PASSWORD,
		maxRetriesPerRequest: 3,
		enableReadyCheck: true,
		connectTimeout: 5000,
		keyPrefix: 'portfolio:',
		semanticKeyPrefix: 'portfolio:sem:',
		defaultExpiration: 3600,
		defaultHost: 'localhost',
		defaultPort: 6379,
	},
	nodemailer: {
		host: process.env.MAIL_HOST,
		port: 465,
		auth: {
			user: process.env.MAIL_USER,
			pass: process.env.MAIL_PASS,
		},
		to: 'contact@msliwowski.net',
	},
	analytics: {
		GA_ID: process.env.GA_ID,
		BASE_URL: process.env.BASE_URL,
		CLIENT_MAIL: process.env.GOOGLE_CLIENT_MAIL,
		PRIVATE_KEY: process.env.GOOGLE_PRIVATE_KEY,
		PROPERTY_ID: process.env.GA4_PROPERTY_ID,
	},
	winston: {
		errorLevel: 'error',
		infoLevel: 'info',
		datePattern: 'YYYY-MM-DD',
		maxFiles: '3d',
		zippedArchive: false,
	},
	assistantConfig: {
		apiKey: process.env.ANTHROPIC_API_KEY,
		model: process.env.ANTHROPIC_MODEL ?? 'claude-sonnet-4-5-20250929',
		maxIterations: Number.parseInt(process.env.ASSISTANT_MAX_ITERATIONS ?? '5'),
	},
	assistantCache: {
		contentVersion: process.env.ASSISTANT_CONTENT_VERSION ?? '1.0.0',
		ttlSeconds: Number(process.env.ASSISTANT_CACHE_TTL) || 60 * 60 * 24,
		maxMessageLength: Number(process.env.ASSISTANT_MAX_MESSAGE_LENGTH) || 500,
		semantic: {
			enabled: process.env.ASSISTANT_SEMANTIC_CACHE_ENABLED === 'true',
			similarityThreshold: Number(process.env.ASSISTANT_SEMANTIC_THRESHOLD) || 0.93,
			circuitFailures: 5,
			circuitCooldownMs: 60_000,
		},
	},
	ollama: {
		host: process.env.OLLAMA_BASE_URL || 'http://ollama-embedding:11434',
		embedModel: process.env.OLLAMA_EMBED_MODEL || 'mxbai-embed-large',
		embedTimeoutMs: Number(process.env.OLLAMA_EMBED_TIMEOUT_MS) || 3000,
		keepAlive: -1 as const,
		embeddingDimensions: 1024,
	},
} as const;
